# Triggers when you push a version tag (v*)
# Logs into Docker Hub
# Builds and pushes all microservice images using Jib

name: Release to Docker Hub

on:
  push:
    tags:
      - 'v*'

jobs:
  push-to-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Images
        run: |
          mvn clean package jib:build -DskipTests \
            -Djib.to.auth.username=${{ secrets.DOCKERHUB_USERNAME }} \
            -Djib.to.auth.password=${{ secrets.DOCKERHUB_TOKEN }}
